// examples/frameworks/react/javascript/pdf-export/src/App.js
/**
 * The App file. It should stay as simple as possible
 */

import React, { Fragment, useRef } from 'react';

import {
    BryntumDemoHeader,
    BryntumGantt,
    BryntumButton
} from '@bryntum/gantt-react';
import { ganttConfig } from './AppConfig';
import './App.scss';

const App = () => {
    const ganttRef = useRef(null);

    const onExportClick = () => {
        ganttRef.current.instance.features.pdfExport.showExportDialog();
    };

    return (
        <Fragment>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader />
            <div className="demo-toolbar align-right">
                <BryntumButton
                    text="Export to PDF/PNG"
                    cls="b-deep-orange b-raised"
                    onClick={onExportClick}
                />
            </div>
            <BryntumGantt
                ref={ganttRef}
                {...ganttConfig}
            />
        </Fragment>
    );
};

export default App;

// examples/frameworks/vue/javascript/pdf-export/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
        <bryntum-demo-header />
        <div class="demo-toolbar align-right">
            <bryntum-button
                cls="b-deep-orange b-raised"
                text="Export to PDF/PNG"
                @click="exportHandler"
            />
        </div>
        <bryntum-gantt
            ref="gantt"
            v-bind="ganttConfig"
        ></bryntum-gantt>
    </div>
</template>

<script>
import {
    BryntumGantt,
    BryntumDemoHeader,
    BryntumButton
} from '@bryntum/gantt-vue';
import { ganttConfig } from '@/AppConfig.js';

export default {
    name : 'app',

    // local components
    components : {
        BryntumDemoHeader,
        BryntumGantt,
        BryntumButton
    },

    data() {
        return {
            ganttConfig
        };
    },

    methods : {
        exportHandler() {
            this.$refs.gantt.instance.features.pdfExport.showExportDialog();
        }
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>
