// examples/frameworks/react/javascript/gantt-schedulerpro/src/App.js
/**
 * Application
 *
 * Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately.
 */

import React, { useEffect, useRef } from 'react';

import {
    BryntumDemoHeader,
    BryntumGantt,
    BryntumSchedulerPro,
    BryntumSplitter,
    BryntumButton
} from '@bryntum/gantt-react';
import { Toast } from '@bryntum/gantt';

import { ganttConfig, schedulerConfig } from './AppConfig';
import './App.scss';

const App = () => {

    const ganttRef = useRef();
    const schedulerRef = useRef();

    useEffect(() => {
        schedulerRef.current.instance.addPartner(ganttRef.current.instance);

        Toast.show({
            timeout : 3000,
            html    : 'Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately.'
        });

    }, []);

    // ZoomIn/ZoomOut handler
    const zoom = action => {
        ganttRef.current.instance[`zoom${action}`]();
    };

    return (
        <>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader
                children={
                    <>
                        <BryntumButton
                            icon="b-icon-search-plus"
                            cls="b-raised b-blue"
                            tooltip="Zoom In"
                            onClick={() => zoom('In')}
                        />
                        <BryntumButton
                            icon="b-icon-search-minus"
                            cls="b-raised b-blue"
                            tooltip="Zoom Out"
                            onClick={() => zoom('Out')}
                        />
                    </>
                }
            />
            <div
                style={{
                    display       : 'flex',
                    flexDirection : 'column',
                    flex          : 1
                }}
            >
                <BryntumGantt
                    ref={ganttRef}
                    {...ganttConfig}
                />
                <BryntumSplitter />
                {/* Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately. */}
                <BryntumSchedulerPro
                    ref={schedulerRef}
                    {...schedulerConfig}
                />
            </div>
        </>
    );
};

export default App;

// examples/frameworks/vue/javascript/gantt-schedulerpro/src/App.vue
<!-- Application -->
<!-- Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately. -->
<template>
    <div id="container">
        <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
        <bryntum-demo-header>
            <bryntum-button
                icon="b-fa-search-plus"
                tooltip="Zoom In"
                cls="b-raised b-blue"
                @click="onZoom('In')"
            />
            <bryntum-button
                icon="b-fa-search-minus"
                tooltip="Zoom Out"
                cls="b-raised b-blue"
                @click="onZoom('Out')"
            />
        </bryntum-demo-header>

        <bryntum-gantt
            ref="gantt"
            v-bind="ganttConfig"
        />
        <bryntum-splitter />
        <bryntum-scheduler-pro
            ref="scheduler"
            v-bind="schedulerConfig"
        />
    </div>
</template>

<script>
import {
    BryntumDemoHeader,
    BryntumGantt,
    BryntumSplitter,
    BryntumSchedulerPro,
    BryntumButton
} from '@bryntum/gantt-vue';
import { Toast } from '@bryntum/gantt';

import { ganttConfig, schedulerConfig } from '@/AppConfig';

export default {
    name : 'App',

    components : {
        BryntumDemoHeader,
        BryntumGantt,
        BryntumSplitter,
        BryntumSchedulerPro,
        BryntumButton
    },

    methods : {
        onZoom(action) {
            this.$refs.gantt.instance[`zoom${action}`]();
        }
    },

    mounted() {
        this.$refs.scheduler.instance.addPartner(this.$refs.gantt.instance);

        Toast.show({
            timeout : 3000,
            html    : 'Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately.'
        });

    },

    data() {
        return { ganttConfig, schedulerConfig };
    }
};
</script>

<style lang="scss">
@import "./App.scss";
</style>
