// docs/data/Scheduler/examples/guides/tutorial/minimal-vue3.vue
<script setup>
import '@bryntum/scheduler'
import { BryntumScheduler } from '@bryntum/scheduler-vue-3'
import '@bryntum/scheduler/scheduler.material.css'
</script>

<template>
    <bryntum-scheduler
            :width="800"
            :height="600"
            start-date="2023-04-16"
            end-date="2023-05-15"
    ></bryntum-scheduler>
</template>

<style>

</style>

// docs/data/Scheduler/examples/guides/tutorial/minimal-react.jsx
import { BryntumScheduler } from '@bryntum/scheduler-react';
import './App.css';

function App() {
    return (
        <>
            <BryntumScheduler
                width={800}
                height={600}
                startDate="2023-04-16"
                endDate="2023-05-15"
            />
        </>
    );
}

export default App;
