// examples/frameworks/vue-3/javascript/gantt-schedulerpro/src/App.vue
<!-- Application -->
<!-- Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately. -->
<template>
    <div id="container">
        <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
        <bryntum-demo-header>
            <bryntum-button
                icon="b-fa-search-plus"
                tooltip="Zoom In"
                cls="b-raised b-blue"
                @click="onZoom('In')"
            />
            <bryntum-button
                icon="b-fa-search-minus"
                tooltip="Zoom Out"
                cls="b-raised b-blue"
                @click="onZoom('Out')"
            />
        </bryntum-demo-header>
        <bryntum-gantt
            ref="gantt"
            v-bind="ganttConfig"
        />
        <bryntum-splitter />
        <bryntum-scheduler-pro
            ref="scheduler"
            v-bind="schedulerConfig"
        />
    </div>
</template>

<script>
import { onMounted, ref } from 'vue';
import {
    BryntumDemoHeader,
    BryntumGantt,
    BryntumSplitter,
    BryntumSchedulerPro,
    BryntumButton
} from '@bryntum/gantt-vue-3';
import { Toast } from '@bryntum/gantt';

import { ganttConfig, schedulerConfig } from '@/AppConfig';

export default {
    name : 'App',

    components : {
        BryntumDemoHeader,
        BryntumGantt,
        BryntumSplitter,
        BryntumSchedulerPro,
        BryntumButton
    },

    setup() {

        const gantt = ref(null);
        const scheduler = ref(null);

        const onZoom = action => {
            gantt.value.instance.value[`zoom${action}`]();
        };

        onMounted(() => {
            scheduler.value.instance.value.addPartner(gantt.value.instance.value);

            Toast.show({
                timeout : 3000,
                html    : 'Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately.'
            });

        });

        return {
            ganttConfig,
            schedulerConfig,
            gantt,
            scheduler,
            onZoom
        };
    }
};
</script>

<style lang="scss">
@import "./App.scss";
</style>

// examples/frameworks/angular/gantt-schedulerpro/src/app/app.component.ts
/**
 * App component script
 */
import { AfterViewInit, Component, ViewChild, ViewEncapsulation } from '@angular/core';
import { Gantt, SchedulerPro, Toast } from '@bryntum/gantt';

import { BryntumGanttComponent, BryntumSchedulerProComponent } from '@bryntum/gantt-angular';
import { ganttConfig, project, schedulerProConfig } from './app.config';

@Component({
    selector      : 'app-root',
    templateUrl   : './app.component.html',
    styleUrls     : ['./app.component.scss'],
    encapsulation : ViewEncapsulation.None
})
export class AppComponent implements AfterViewInit {

    project = project;
    public ganttConfig = ganttConfig;
    public schedulerProConfig = schedulerProConfig;

    private gantt!: Gantt;
    private schedulerPro!: SchedulerPro;

    @ViewChild('gantt') ganttComponent!: BryntumGanttComponent;
    @ViewChild('schedulerpro') schedulerProComponent!: BryntumSchedulerProComponent;

    ngAfterViewInit(): void {
        this.gantt = this.ganttComponent.instance;
        this.schedulerPro = this.schedulerProComponent.instance;
        this.schedulerPro.addPartner(this.gantt);

        Toast.show({
            timeout : 3000,
            html    : 'Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately.'
        });
    }
}

<!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
<bryntum-demo-header></bryntum-demo-header>

<bryntum-gantt
    #gantt
    [project] = "project"
    [resourceImageFolderPath] = "ganttConfig.resourceImageFolderPath!"
    [flex] = "ganttConfig.flex!"
    [labelsFeature] = "ganttConfig.features!.labels!"
    [viewPreset] = "ganttConfig.viewPreset!"
    [columnLines] = "ganttConfig.columnLines!"
    [columns] = "ganttConfig.columns!"
    [startDate] = "ganttConfig.startDate!"
    [listeners] = "ganttConfig.listeners!"
    [subGridConfigs] = "ganttConfig.subGridConfigs!"
></bryntum-gantt>
<bryntum-splitter></bryntum-splitter>
<bryntum-scheduler-pro
    #schedulerpro
    [project] = "project"
    [flex] = "schedulerProConfig.flex!"
    [rowHeight] = "schedulerProConfig.rowHeight!"
    [eventColor] = "schedulerProConfig.eventColor!"
    [useInitialAnimation] = "schedulerProConfig.useInitialAnimation!"
    [resourceImagePath] = "schedulerProConfig.resourceImagePath!"
    [dependenciesFeature] = "schedulerProConfig.features!.dependencies!"
    [percentBarFeature] = "schedulerProConfig.features!.percentBar!"
    [columns] = "schedulerProConfig.columns!"
></bryntum-scheduler-pro>
