// examples/frameworks/vue/javascript/vue-renderer/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
        <bryntum-demo-header />
        <bryntum-gantt
            v-bind="ganttConfig"
        />
    </div>
</template>

<script>
import { BryntumDemoHeader, BryntumGantt } from '@bryntum/gantt-vue';
import { ganttConfig } from '@/AppConfig';

export default {
    name : 'App',

    components : {
        BryntumGantt,
        BryntumDemoHeader
    },

    data() {
        return { ganttConfig };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// examples/frameworks/react/javascript/taskeditor/src/App.js
/**
 * The App file. It should stay as simple as possible
 */

import React, { Fragment } from 'react';
import { BryntumDemoHeader, BryntumGantt } from '@bryntum/gantt-react';
import { ganttConfig } from './AppConfig';
import './App.scss';

const App = () => {
    return (
        <Fragment>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader />
            <BryntumGantt
                {...ganttConfig}
            />
        </Fragment>
    );
};

export default App;
