// examples/frameworks/react/typescript/basic/src/App.tsx
/**
 * Main Application script
 */
import React, { Fragment, FunctionComponent } from 'react';

import { BryntumDemoHeader, BryntumGantt } from '@bryntum/gantt-react';
import { ganttConfig } from './AppConfig';
import './App.scss';

const App: FunctionComponent = () => {
    return (
        <Fragment>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader/>
            <BryntumGantt {...ganttConfig} />
        </Fragment>
    );
};

export default App;

// examples/frameworks/vue/javascript/advanced/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
        <bryntum-demo-header />
        <bryntum-gantt-project-model
            ref="project"
            v-bind="projectConfig"
            :taskModelClass="Task"
        />
        <bryntum-gantt
            v-bind="ganttConfig"
            :project="project"
        />
    </div>
</template>

<script>
import { BryntumDemoHeader, BryntumGantt, BryntumGanttProjectModel } from '@bryntum/gantt-vue';
import { projectConfig, ganttConfig } from '@/AppConfig';
import Task from '@/lib/Task.js';

export default {
    name : 'app',

    components : {
        BryntumDemoHeader,
        BryntumGantt,
        BryntumGanttProjectModel
    },
    mounted() {
        // Set project so that gantt can use it
        this.project = this.$refs.project;
    },
    data() {
        return {
            projectConfig,
            ganttConfig,
            Task,
            project : null
        };
    }
};
</script>

<style lang="scss">
@import "./App.scss";
</style>
